### ISSUE TITLE
Update data documentation

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/ranktreeEnsemble#1]
Hi folks,
Because the main strength of the TSP method is to avoid batch effects, the "tnbc.rda" example data should not contain data only from one assay. The documentation file states that sample values "were randomly chosen from the original dataset". If this original data set included samples from many different batches, then this should be made clear in the documentation. If not, then samples from other "batches" should be included to show the strength of the method as a true "single sample classifier".

**Comment by gabrielodom** [comment]
From the manuscript, "We downloaded other three datasets [38–40] and trained our models on data from one platform (e.g. microarray) while tested its prediction performance on data from another platform (e.g. RNA-seq)." So, it appears that the "tnbs.rda" data set does include samples from multiple platforms, so this should be made clear in the documentation (including a count of how many samples are drawn from which platforms).

**Comment by luminwin** [comment]
Thank you for your comments and we are working on it.
