### ISSUE TITLE
Use S3 method dispatch or a class-specific build for `predict()` generic

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/ranktreeEnsemble#2]
The `predict()` function is currently masking the `predict.<class>()` generic from the `stats::` package. This should be written as an S3 method for objects of class `rfsrc` so that it **extends** the `stats::predict()` generic rather than masking it. Note that the help documentation already states that the `object` argument must be an "object of class \code{rfsrc}", so this issue is simply to make the code do what the documentation says it does.

**Comment by gabrielodom** [comment]
I'm looking more intently at this `predict()` function, and you already use a whole host of `if()` statements anyway. When you refactor this function as one generic (`predict.<class>()`) and many methods (`predict.gbm()`, `predict.rfsrc()`, etc), your code will interoperate better with existing R packages and will be easier to maintain in the future.

**Comment by luminwin** [comment]
Thank you for your comments and we are working on it.
