### ISSUE TITLE
Use `message()` instead of `cat()` to display information during computing

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/ranktreeEnsemble#3]
It is good function/package development practice to use `message()` instead of `cat()` or `print()` calls when displaying diagnostic messages. See this discussion: <https://stackoverflow.com/a/36700294/8366590>. For progress bars specifically, `cat()` is probably fine, but include a function option `verbose = TRUE` (default) which gives users the ability to turn this off. Overall, this comment is more related to managing the side effects of functions.

**Comment by gabrielodom** [comment]
Example: `rboost()` prints this message to the user: "n.trees not given. Using 100 trees."
This should be coded using the `message()` function (but this message may be coming from `gbm()` and not directly from `rboost()`). If there are functions in this package which give "messages" or "notes" to the user, they should be displayed with the `message()` function.

**Comment by luminwin** [comment]
Thank you for your comments and we are working on it.
