### ISSUE TITLE
Unexpected warning for `predict()` on output of `select.rules()`

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/ranktreeEnsemble#4]
When I run the example in the README, I get the following warning:

```
objrs <- select.rules(objr,tnbc[110:130,c(1:5,337)])
predict(objrs, tnbc[111:120,1:5])$label
```
```
Warning messages:
1: In `==.default`(colnames(newdata), yvar.names) :
  longer object length is not a multiple of shorter object length
2: In is.na(e1) | is.na(e2) :
  longer object length is not a multiple of shorter object length
```

If this is on purpose, then the warning message should be explicit and informative. Currently, I do not know what this warning message is trying to tell me. If this warning message is not what I should expect, then please dig into the code and find out why it's showing up.

In summary: if the warning is supposed to be there, then re-write the warning message to be more clear (and change this issue from "bug" to "documentation"). If the warning is not supposed to be there, please troubleshoot your code.

**Comment by luminwin** [comment]
Thank you for your comments and we are working on it.
