### ISSUE TITLE
`gbm()` does not support multinomial outcomes

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/ranktreeEnsemble#5]
In the README, we have this example (and subsequent warning):

```
objb <- rboost(subtype~., data = tnbc[1:100,c(1:5,337)])
```
```
Warning messages:
1: Setting `distribution = "multinomial"` is ill-advised as it is currently broken. It exists only for backwards compatibility. Use at your own risk. 
2: Setting `distribution = "multinomial"` is ill-advised as it is currently broken. It exists only for backwards compatibility. Use at your own risk. 
```

If the maintainers of the `gbm::` package advise against using their functions for multinomial data, why does this package depend on and endorse this? This is is confusing. Please switch to a package which supports multinomial responses, or drop this example from the README and paper.

**Comment by luminwin** [comment]
Thank you for your comments and we are working on it.
